Add custom textstyle for the name property in a golden test scenario,…
Betterment/alchemist pull request #115
Opened 2024-09-06 13:23 UTC by NRijnberg

## Description
Add custom textstyle for the name property in a golden test scenario, this is very useful when your default bodyMedium has a white text color, and the background of the golden test is white as well, this way you can make it visible by providing your own text style

## Type of Change
- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

2024-09-06 13:54 UTC, jeroen-meijer requested changes
Some minor changes but LGTM otherwise

2024-09-06 13:54 UTC, jeroen-meijer commented on lib/src/golden_test_scenario.dart
> +            style: nameTextStyle ?? const TextStyle(fontSize: 18),
```suggestion
            style: const TextStyle(fontSize: 18).merge(nameTextStyle),
```

2024-09-06 13:54 UTC, jeroen-meijer commented on lib/src/golden_test_scenario.dart
> +            constraints: constraints ?? GoldenTestScenarioConstraints.maybeOf(context) ?? const BoxConstraints(),
Why this change?

2024-09-06 13:54 UTC, jeroen-meijer commented
@btrautmann @Kirpal I'll leave merging and release up to you. I don't see any issues with this change. 👌🏻

2024-09-06 22:24 UTC, jeroen-meijer approved these changes

2024-09-10 15:16 UTC, btrautmann commented
@NRijnberg I'm working on getting this unblocked with an upgrade to 3.16.0.

2024-09-11 17:07 UTC, btrautmann commented
@NRijnberg I just merged a PR that bumps the min version for Flutter/dart to a version compatible with your PR, so you should be able to rebase and push. Once that's done/in, I'll be able to merge and cut a new version.

2024-09-12 21:04 UTC, btrautmann commented
I ended up cutting 0.8.0 rather than waiting for this, but feel free to get this back into a good state and we can cut a new version.

2024-11-14 20:11 UTC, btrautmann commented
Closing in favor of https://github.com/Betterment/alchemist/pull/132.

2024-11-14 20:11 UTC, closed without merging