feat: Improve reliability, add unit tests
Betterment/alchemist pull request #19
Opened 2022-03-04 16:32 UTC by definitelyokay

## Description

Refactors Alchemist to fix an issue with pending timers still being present when golden testing certain widgets. Alchemist was performing `ci` and `platform` golden tests inside of the same `testWidgets` call, which does not allow for pending timers to be flushed through the event loop on certain machines (or perhaps through the fakeasync machinery used under the hood by `flutter_test`). We noticed the problem on my Apple Silicon machine, but not on @Kirpal's intel mac.

After some investigation, we realized that using an individual `testWidgets` call for each golden test allows `flutter_test` to properly cleanup after a widget. We took advantage of `flutter_test`'s `TestVariant` system, which enable us to perform a `testWidgets` call for each platform that a golden test is configured to run on.

While making and testing this change, we refactored additional pieces of Alchemist so that it could be properly unit-tested. To preserve confidence of Alchemist's total behavior, we have created a new `smoke_tests` folder inside of `./test`, which can contain proper golden tests (which are effectively integration tests on Alchemist itself) and regression scenarios.

We have added our first regression scenario in `test/smoke_tests/timer_button_smoke_test.dart`:

```dart
import 'dart:async';

import 'package:alchemist/src/golden_test.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class TimerButton extends StatelessWidget {
  const TimerButton({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      child: const Text('Button'),
      onPressed: () {
        Timer(Duration.zero, () {});
      },
    );
  }
}

void main() {
  group('smoke test', () {
    goldenTest(
      'succeeds after tapping button with timer',
      fileName: 'timer_button_smoke_test',
      pumpBeforeTest: (tester) async {
        await tester.tap(find.byType(TimerButton));
        await tester.pumpAndSettle();
      },
      widget: const TimerButton(),
    );
  });
}
```

### Public API Changes

A few minor public API changes have been made.

- `TestComparisonPredicate` has been removed. We think everything it can do can be done with test tags, so we'd rather encourage the use of those since they're a vanilla part of `flutter_test`.
-  `PlatformGoldensConfig` and `CiGoldensConfig` share the same superclass, `GoldensConfig`. Doing so greatly simplified the `TestVariant` implementation.
- `FilePathResolver` now has a `FutureOr<String>` return type for convenience.

### Structural Changes

To enable Alchemist to be unit-tested, Alchemist's had to be uncoupled from `flutter_test` directly. Alchemist now consists of several layers that work together, each of which can be mocked, faked, or stubbed as needed for individual testing.

At the public level, `goldenTest` uses a `GoldenTestRunner` and `GoldenTestAdapter` to interface with `flutter_test`.

Throughout Alchemist, there are now various globals that allow for easy overriding in tests. These usually appear in little groups, like the `testWidgetsFn` override in `golden_test_adapter`:

```dart
/// Default testWidgets function that simply points to Flutter's [testWidgets].
TestWidgetsFn defaultTestWidgetsFn = testWidgets;
TestWidgetsFn _testWidgetsFn = defaultTestWidgetsFn;

/// A function to be used in place of `flutter_test`'s `testWidgets` function.
/// The ability to use a stub method here makes it easier to test Alchemist.
TestWidgetsFn get testWidgetsFn => _testWidgetsFn;
set testWidgetsFn(TestWidgetsFn value) => _testWidgetsFn = value;
```

This style of these global overrides is itself inspired by the source for `matchesGoldenFile`, which allows for its own `goldenFileComparator` to be overridden.

Likewise, the override functionality of `HostPlatform` was refactored to match this approach for the sake of consistency.

@jeroen-meijer If you have a chance, would love your insight on all this before we do anything crazy.

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [x] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

2022-03-07 15:48 UTC, Kirpal commented on test/src/alchemist_config_test.dart
> +        currentHostPlatform = hostPlatform;
```suggestion
        hostPlatform = currentHostPlatform;
```

2022-03-07 19:44 UTC, Kirpal requested changes
Looks really good overall. Had a couple of suggestions. Also, are we sure we want to strip text packages by default? I'm thinking that might be a specific need for Betterment, so maybe we should remove that functionality and just strip the text package before passing in the theme.

2022-03-07 19:44 UTC, Kirpal commented on lib/src/alchemist_config.dart
> +  /// Whether of not all text should be rendered as colored boxes
```suggestion
  /// Whether or not all text should be rendered as colored boxes
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/alchemist_config_test.dart
> +            : HostPlatform.linux;
```suggestion
        nextHostPlatform = HostPlatform.values.firstWhere((platform) => currentHostPlatform != platform);
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/host_platform_test.dart
> +          : HostPlatform.linux;
```suggestion
      final nextHostPlatform = HostPlatform.values.firstWhere((platform) => platform != hostPlatform);
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/alchemist_test_variant_test.dart
> +      });
```suggestion
      test('setUp sets current value', () async {
        final value = MockCiGoldensConfig();
        await expectLater(
          variant.setUp(value),
          completes,
        );
        expect(variant.currentConfig, value);
      });

      test('describeValue returns environment name', () async {
        final value = MockCiGoldensConfig();
        const environmentName = 'TEST';
        when(() => value.environmentName).thenReturn(environmentName);
        expect(variant.describeValue(value), environmentName);
      });
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/golden_test_runner_test.dart
> +      tearDownAll(() {
```suggestion
      tearDown(() {
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/golden_test_test.dart
> +      );
```suggestion
      ).called(1);
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/golden_test_test.dart
> +      verify(
```suggestion
      verifyNever(
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/golden_test_adapter_test.dart
> +      });
```suggestion
      test('overrides value', () {
        testWidgetsFn = customTestWidgets;
        expect(testWidgetsFn, customTestWidgets);
        testWidgetsFn = defaultTestWidgetsFn;
      });
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/golden_test_adapter_test.dart
> +      });
```suggestion
      test('overrides value', () {
        setUpFn = customSetUp;
        expect(setUpFn, customSetUp);
        setUpFn = defaultSetUpFn;
      });
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/golden_test_adapter_test.dart
> +      });
```suggestion
      test('overrides value', () {
        tearDownFn = customTearDown;
        expect(tearDownFn, customTearDown);
        tearDownFn = defaultTearDownFn;
      });
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/golden_test_adapter_test.dart
> +      });
```suggestion
      test('overrides value', () {
        goldenFileExpectationFn = customExpectation;
        expect(goldenFileExpectationFn, customExpectation);
        goldenFileExpectationFn = defaultGoldenFileExpectation;
      });

      test('original value invokes matchesGoldenFile', () async {
        try {
          goldenFileExpectationFn(1, 2);
          fail('expected matchesGoldenFile to be invoked');
        } catch (e) {
          expect(
            e,
            isA<TestFailure>().having(
              (testFailure) => testFailure.message,
              'message',
              contains('matchesGoldenFile'),
            ),
          );
        }
      });
```

2022-03-07 19:44 UTC, Kirpal commented on test/src/golden_test_adapter_test.dart
> +      tearDownAll(() {
```suggestion
      tearDown(() {
```

2022-03-08 15:23 UTC, merged

2022-03-08 23:10 UTC, definitelyokay commented
@Kirpal Thank you for taking over this while I'm out 🚀